wntr/graphics/color.py
wntr/graphics/curve.py
wntr/graphics/network.py

This PR removes the hard dependency on matplotlib.  Matplotlib is only required if you use functionality in wntr.graphics and if you run the tests and examples.  wntr can be imported without matplotlib installed.

 Removed hard dependency on matplotlib

---

examples/resilience_metrics.py
examples/stochastic_simulation.py
examples/water_quality_simulation.py
wntr/epanet/io.py
wntr/metrics/misc.py
wntr/morph/skel.py

This PR contains several updates, including:
* Updated population metric to use `average_expected_demand` (which is the average over 1 day) instead of the average of `expected_demand` (which uses the simulation start and end time as default)
* Updated BinFile.read to create a new results object each time it is called
* Renamed demand category to None when merging demands in skeletonization
* Minor updates to examples

Minor updates to the population metric, epanet IO, skeletonization, and examples

---

wntr/network/controls.py

Addresses #79 
Note: 
The USEPA/WNTR GitHub site, https://github.com/USEPA/WNTR, does not link to Travis CI for continuous integration software testing.  
The core development team uses the sandialabs/WNTR fork, https://github.com/sandialabs/wntr, to run tests.
To submit a Pull Request to USEPA/WNTR, the developer needs to link their fork to Travis so that test results can be inspected.
If the developer does not have Travis linked to their fork, the Pull Request can be submitted to the sandialabs/WNTR fork.

bug in AndCondition.requires

---

documentation/waterquality.rst
documentation/whatsnew.rst
documentation/whatsnew/v0.2.2.1.rst
wntr/__init__.py
wntr/network/model.py
wntr/tests/test_network.py

This PR fixes #137.  The assign_demand function now updates demands using the demand_timeseries_list and the function uses the demand multiplier to create a new pattern.  
The input DataFrame that contains new demands can only include junctions as column names, Therefore, if you are using demands that come from simulation results, you need to extract column names associated with junctions.  For example, `results.node['demand'].loc[:,wn.junction_name_list]`.  
The documentation has been updated and tests were added.  
Travis CI test results are available at https://travis-ci.org/github/kaklise/WNTR/builds/685793237

Fixed assign_demand

---

documentation/whatsnew/v0.2.2.1.rst
wntr/network/controls.py
wntr/network/model.py
wntr/sim/models/constraint.py

This PR addresses issues with the WNTRSimulator controls that were identified when working on #108. Updates include:
* Fixed a bug in tank controls that are used when a pipe entering/leaving the tank has a CV
* Fixed a bug in the PSV headloss constraint, which now uses elevation at the start node
* Added a tolerance threshold to ValueCondition and TankLevelCondition
* Added a tolerance threshold to the condition that activates FCV
Travis CI test results are available at https://travis-ci.org/github/kaklise/WNTR/builds/686229500

Updates to WNTRSimulator controls

---

wntr/epanet/io.py

Since there is no dev branch on the sandialabs/WNTR fork, I decided to create the pull request here.
Using some more complex INP files, I found that the read_pipes functionality did not cover the epanet functionalities.
The last two columns (minor losses and status) are optional in epanet engine, but are enforced here. Giving rise to some failures when loading an INP file. The current pull request overcomes the current issue and is more in line with Epanet.

Make INP reading more robust, based on epanet documentation

---

examples/getting_started.py

adding description to getting_started example from docs
``` 
The following example runs a simple example that uses EPANET Example Network 3 (Net3). This example demonstrates how to:
* Import WNTR
* Generate a water network model
* Simulate hydraulics
* Plot simulation results on the network
```

adding description to getting_started example

---

documentation/resultsobject.rst
wntr/epanet/io.py
wntr/network/base.py
wntr/network/controls.py
wntr/network/elements.py
wntr/network/model.py
wntr/sim/hydraulics.py
wntr/tests/test_models.py
wntr/tests/test_network_controls.py
wntr/tests/test_sim_benchmark.py

Addresses bug #185 
Also changed:
- Making simulation values (outputs) non-writable and adding in missing ones (as compared to EPANET) into the classes.
- Also making internal properties private rather than public, and using setters/getters to handle protecting private attributes and doing type checking.
- changed results objects to use consistent names for links:
- "reaction_rate" instead of "rxnrate" 
- "quality" instead of "linkquality"
- "friction_factor" instead of "frictionfact"

Fix missing output attributes that impacted control actions

---

wntr/epanet/io.py

When running a simulation with the Epanet Simulator the original INP file is copied into a temp.inp
If a pump has a setting SPEED of 1.0 this value is not passed to the temp.inp
The check of SPEED is made as "!= 1", however it must be if "is not None" 
** other checks must be passed SPEED is float or int, SPEED > 0

PUMP SPEED != 1

---

wntr/graphics/network.py
wntr/tests/test_graphics.py

This PR fixes an error in `plot_network` related to #205

Bug fix for plotting directed networks with link attributes

---

documentation/whatsnew/v0.3.1.rst
wntr/epanet/io.py
wntr/sim/hydraulics.py

This PR includes the following two updates:
- Changed ABOVE and BELOW keywords in controls from >= and <= to > and < 
- Added a NotImplementedError if D-W or C-M is used with the WNTRSimulator

Update to controls and added a NotImplementedError for D-W and C-M

---

wntr/epanet/io.py

Hello, I encountered some problems when using WNTR to read INP files. I got an error message `Time format in INP file not recognized.`
Because `QUALITY TIMESTEP 0.08` is set in the inp `[TIMES]` section
According to the description of the [`[TIMES]` section in the Epanet document](https://epanet22.readthedocs.io/en/latest/input_keywords.html#times), `If no units are supplied, then time values can be expressed in either decimal hours or in hours:minutes notation.`
But WNTR only supports hours:minutes notation, so I updated the code to allow the `[TIMES]` section to be able to set the time value in decimal format.

Update io.py - time format allow decimal hours

---

.gitignore
documentation/framework.rst
documentation/users.rst
documentation/whatsnew.rst
documentation/whatsnew/v0.4.0.rst
documentation/whatsnew/v0.4.1.rst
wntr/__init__.py
wntr/network/elements.py
wntr/network/model.py
wntr/sim/models/param.py
wntr/sim/models/var.py
wntr/tests/test_epanet_toolkit.py
wntr/tests/test_sim_demand_multiplier.py
wntr/tests/test_sim_reset_conditions.py

The following PR adds the ability to use a pattern start time with the WNTRSimulator.  This PR also removes a private attribute from pumps that is no longer needed to model power outages, updates the user community webpage, and renamed some files created in tests.

Added pattern start to the WNTRSimulator

---

wntr/network/options.py

This PR forces the hydraulic, quality, pattern and rule timestep to be a minimum of 1 second and forces them to be integer seconds. This prevents problems with rounding errors resulting in 0-size timesteps.

Min timestep

---

.gitignore
wntr/network/controls.py
wntr/tests/test_network_controls.py

I wanted to experiment with changing Control/Rule parameters but found the current workflow more complex than it needed to be:
1. Find the rule you want to change
2. Extract the parameters you want to remain the same
3. Remove the rule
4. Create a new rule and add it to the network
So I decided to implement the following workflow:
1. Find the rule you want to change
2. Update the parameters you want to change
I have made the following changes to facilitate this:
1.  `wntr.network.controls.Control` inherited from `wntr.network.controls.Rule` and had very similar `__init__`, now `wntr.network.controls.Control` uses `super().__init__()` to simplify this and reduce code duplication
2. I added the following methods to `wntr.network.controls.Rule`: `update_condition`, `update_then_actions`, …

Added ability to easily update Control/Rule parameters

---

MANIFEST.in
setup.py

This PR includes the inp files used for testing in `MANIFEST.in` so they get distributed with WNTR. This allows at least a subset of the tests to be run after installing WNTR.

Distribute inp files used for testing

---

documentation/getting_started.rst
wntr/graphics/curve.py
wntr/graphics/network.py

This PR adds plt.show(block=False) to matplotlib graphics within WNTR, including network plots and plots that show curves.    This ensures that graphics are shown when running WNTR outside Spyder.  If running examples directly from the command line, Python should be run in interactive mode (for example, python -i file.py).  Docs were updated to describe.  Using block=False ensures that the tests continue running after a graphic is created.

Graphics update to include plt.show()

---

wntr/epanet/util.py
wntr/tests/test_epanet_units.py

This PR includes a bug fix for emitter coefficient unit conversion between flowunit/sqrt(psi) and flowunit/sqrt(m).  The conversion now uses 0.4333 psi/ft and 0.3048 m/ft to match the way pressure is converted in WNTR.  The corrected conversion is flowunit/sqrt(psi) * sqrt( 0.4333 psi/ft / 0.3048 m/ft ) = flowunit/sqrt(m).  A test was added that includes all 10 EPANET flowunits.

Emitter units

---

wntr/network/elements.py
wntr/tests/test_network.py

typecast pattern to float prior adding to registry
added specific test for storing network with patterns consisting only of integers
This fixes #271

Fix issue #271

---

documentation/waternetworkmodel.rst

EpanetSimulator was wrongly spelt as EpanetSimualtor in the "Reset initial conditions" section.

doc: Corrected typo

---

documentation/controls.rst

The word "within" was wrongly split to "with in" in the "Conditions" section of "Water network controls".

doc: Corrected a typo

---

.github/workflows/build_tests.yml
.github/workflows/quick_check.yml
.gitignore
documentation/installation.rst
documentation/whatsnew/v0.5.0.rst
setup.py
wntr/tests/test_sim_performance.py

* Added a `--build` input argument to setup.py to build the shared object files 
* Updated developer installation instructions.  Now that the shared object files are not distributed with the code, developers should run `python setup.py develop --build` or download the files from GitHub Actions.
* Updated workflow yml files
* Updated release notes
* Added a buffer to the sequential vs. threading timing test

Added a build input argument to setup.py

---

.gitignore
documentation/gis.rst
wntr/epanet/io.py
wntr/gis/geospatial.py
wntr/morph/node.py
wntr/network/base.py
wntr/tests/test_epanet_io.py
wntr/tests/test_morph.py

Provide a summary of the proposed changes, describe tests and documentation, and review the acknowledgement below. 
This PR resolves issue #283 by including link vertices in the transformations performed on node coordinates.
No new features were added, but new lines have been added to existing tests to cover vertex cases.

Adding vertices to morph.node

---

wntr/epanet/io.py
wntr/epanet/util.py
wntr/network/controls.py
wntr/sim/core.py
wntr/tests/test_sim_performance.py

This PR resolves #329.  Several cases of `type(x) is int` and `type(x) is float` have been updated to use `isinstance(x, (int, float))`
Test added in test_sim_performance.py, this specifically tests the use `np.float64` in `wn.options.time`

Type checking for time options

---

documentation/conf.py
documentation/fragility.rst
documentation/getting_started.rst
documentation/gis.rst
documentation/graphics.rst
documentation/layers.rst
documentation/resilience.rst
wntr/gis/geospatial.py
wntr/tests/test_gis.py

The snap GIS function was updated to use node name as a tie breaker when snap distances between multiple nodes are the same.  This PR also includes documentation updates to improve readability of the user manual when built into a PDF.
- Resolves `test_snap_points_to_lines` on py10
- Minor documentation updates to improve readability

Update in snap GIS function to use node name as a tie breaker

---

wntr/sim/aml/aml.py
wntr/tests/test_aml.py

Currently, when the number of constraints that reference a variable drops to zero, the value stored in the variable is lost. This PR fixes that.

Ensure variables and parameters keep their values when constraints are removed

---

wntr/morph/link.py
wntr/tests/test_morph.py

This PR adds a function that can reverse links direction
The function preserves the link's vertices

add function for reverse links direction

---

documentation/installation.rst
readthedocs.yml
requirements.txt
setup.py

- Added setuptools to required packages
- Removed readthedoc.yml and readthedocs environment variable from setup.py 
Install tested

Added setuptools and removed readthedocs config

---

wntr/epanet/io.py

Related: #409
When the `units` keyword argument is set to "SI" in `write_inp`, WNTR will generate an INP file with values in SI units and the UNITS option set to "SI". The file can be loaded into EPANET file, where the "SI" gets changed to "LPS." No other values seem to be changed in the inp file, but I think that is correct since the only difference between "SI" units and "LPS" would be flow values and maybe pressure, which are not recorded in the inp file. 
I recommend not allowing "SI" to be passed as an argument here as one potential option to address this unintuitive behavior. My PR implements a basic approach by throwing an exception when "SI" is passed. Another option would be to allow "SI", but specify to the user what is happening when they load the "SI" inpfile into EPANET (this …

Addressing bug caused when `units="SI"` in a call to `write_inp()`

---

wntr/graphics/network.py
wntr/tests/test_graphics.py

A change to the behavior the networkx function `draw_networkx_edges` disrupted the colorbar code in wntr's `plot_network` function due to a mismatch in return object. 
The following code in `draw_networkx_edges` occurs in version 3.1 (probably 3.2 as well):
```
use_linecollection = not G.is_directed()
if arrows in (True, False):
use_linecollection = not arrows
```
however this changes to the following in version 3.3:
```
if arrows is None:
use_linecollection = not (G.is_directed() or G.is_multigraph())
else:
if not isinstance(arrows, bool):
raise TypeError("Argument `arrows` must be of type bool or None")
use_linecollection = not arrows
```
The graph we use in `plot_network` is a multigraph, so `use_linecollection` now gets set to False, counter the the previous behavior. When this …

Fix: plot_network bug due to changed networkx draw function behavior

---

.github/workflows/build_deploy_pages.yml
.github/workflows/build_tests.yml
.github/workflows/release.yml
documentation/disaster_models.rst
documentation/environment.yml
documentation/fragility.rst
documentation/gis.rst
documentation/graphics.rst
documentation/installation.rst
documentation/layers.rst
documentation/morph.rst
documentation/resultsobject.rst
documentation/whatsnew.rst
documentation/whatsnew/v1.2.0.rst
requirements.txt
wntr/epanet/io.py
wntr/gis/geospatial.py
wntr/metrics/topographic.py
wntr/network/model.py

The following PR includes minor updates to resolve deprecation and future warnings.  The windows build test now includes GeoPandas, which can be installed through pip. Plotly is no longer set to <=5.11.0. Scipy is still set to <1.13.0.
Installation instructions updated for GeoPandas

Resolved deprecation/future warnings and included GeoPandas in windows build test

---

.gitignore
documentation/morph.rst
wntr/epanet/io.py
wntr/morph/skel.py
wntr/tests/test_morph.py

Provide a summary of the proposed changes, describe tests and documentation, and review the acknowledgement below. 
#347 
Added nodes and links to exclude in the skelenazation process. It is handled in the same manner as the nodes and links with controls. 
Test copied from nodes and links with controls, should have the same impact. 
Two new inputs added to the initialization of the class, so they can be extended to the nodes -links with controls. They could also be separated, but the if statements and the three separate stages are fairly complex, so I didn't want to add another `and` to it. 
Only the naming could now be improved in the if statements, instead nodes_with_controls -> nodes_to_exclude, which makes it easier to read. 
By contributing to this software project, I acknowledge …

Added nodes/pipes to excluded to the skel proc

---

wntr/graphics/network.py

The following update fixes a bug in the link colormap that is created in `plot_network`.  The previous code ignored user input from `link_range` and used only positive values.
The PR also includes minor updates to demos.
NA

Fixed bug in network graphic related to link colormap

---

wntr/graphics/network.py

Solves issue #389 which describes problems using `wntr.graphics.network.network_animation` in Jupyter Notebooks by adding a `show_plot` parameter to the `wntr.graphics.network.plot_network` function. 
`show_plot` is set to 'True' by default on `wntr.graphics.network.plot_network`, but changed to `False` within  `wntr.graphics.network.network_animation`. This makes `network_animation` work as intended.
None; docstring for the `show_plot` parameter of the `wntr.graphics.network.plot_network` function added
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://wntr.readthedocs.io/en/stable/developers.html) and that my contributions are submitted under the [Revised BSD …

Fixing `plt.show()` in `plot_network` for `network_animation`

---

documentation/gis.rst
wntr/gis/geospatial.py
wntr/gis/network.py
wntr/network/io.py
wntr/tests/test_gis.py

Changes default name column from 'index' to 'name' and removes a couple of instances where it was assumed that there was a column 'index'.
Fixes #433 
n/a - not a new feature

Fix #433 - Gis files written with column title 'name'

---

documentation/gis.rst
documentation/model_io.rst
wntr/gis/network.py
wntr/network/elements.py
wntr/network/io.py
wntr/tests/test_gis.py
wntr/tests/test_network.py

The following PR addresses #448 and #449.  `node_type` and `link_type` are no longer stored or used in the WaterNetworkGIS GeoDataFrames.  The attributes are still included in the dictionary representation of WaterNetworkModels which are used to translate between WaterNetworkModels and the GIS data.
Bug fix: Missing commas resulted in errors in the valid GIS names
Bug fix: GeoDataFrames now include valid columns even when all entries in that column are None
- Added a test to compare valid GIS names to gis data
- Updated a test to remove node_type and link_type
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://wntr.readthedocs.io/en/stable/developers.html) and that my contributions are submitted under the …

Bug fix in valid GIS names used to create water network models

---

wntr/epanet/io.py
wntr/epanet/util.py
wntr/network/options.py
wntr/tests/test_epanet_io.py

The following PR addresses #443 regarding unit conversion of the roughness coefficient when using D-W headloss formula.  This update only impacts the EpanetSimulator which requires the unit conversion when reading/writing the INP file. The WNTRSimulator does not support D-W headloss formula.  
The original code did not convert roughness in `_read_pipes` and `_write_pipes`. The `to_si` and `from_si` conversion functions for roughness were also incorrect and updated.
If `wn.options.hydraulic.headloss` is changed from ['H-W', 'C-M'] to/from 'D-W', a UserWarning is printed to the screen.  The units of headloss cannot be converted from unitless to/from length.
Tests were added to `test_epanet_io.py`.  The mean absolute error in pressure values for Net3 is within 0.55 m when using H-W, C-M, and …

Bug fix in roughness unit conversion when using D-W

---

wntr/network/elements.py

To fix #468.
Deprecate Pipe.cv in favour of Pipe.check_valve (as pipe.check_valve is used more frequently already, and is clearer.) 
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://usepa.github.io/WNTR/developers.html) and that my contributions are submitted under the [Revised BSD License](https://usepa.github.io/WNTR/license.html).

Check valve fix

---

.github/workflows/build_tests.yml

This PR is intended to address the problem that our linux wheels are rejected by PYPI. This is because they are generic linux wheels, rather than complying to a manylinux standard. Previous attempts to repair the wheel to a proper manylinux standard have run into difficulties resulting from the compiled EPANET binaries. Since these binaries are out of our control, it is not possible to quickly resolve this issue.
By renaming our linux wheels to appear as manylinux wheels, pypi should accept them. It is important to recognize that this will likely cause issues on some systems which are not actually compatible with the linux wheel, despite the manylinux name. We have tested the wheel on common ubuntu environments (my personal machine (22.04), GH ubuntu-latest (I assume this is 24.X), and on …

Update wheel building to rename linux wheels

---

.github/workflows/build_tests.yml

works around https://github.com/USEPA/WNTR/issues/494 by ad hoc signing the dylibs on Apple Silicon.
do note [limitations](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes) of ad hoc signing:
> However, given that these signatures do not bear any valid identity, binaries signed this way cannot pass through Gatekeeper.
this means this solution is not future proof if Gatekeeper becomes more aggressive on future versions of macOS. the best practice would be to sign with an Apple Developer certificate and ideally notarize. but given the additional resources that would take, i think this is a reasonable workaround for https://github.com/USEPA/WNTR/issues/494.
once the CI for this PR runs, i'll inspect the produced wheels and make …

Ad hoc signing of dylibs for Apple Silicon

---

wntr/gis/geospatial.py

This small PR resolves the GeoPandas deprecation warnings:
```python
D:\a\WNTR\WNTR\wntr\gis\geospatial.py:151: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
````
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://usepa.github.io/WNTR/developers.html) and that my contributions are submitted under the [Revised BSD License](https://usepa.github.io/WNTR/license.html).

Resolve GeoPandas deprecation warnings

---

wntr/network/base.py
wntr/tests/test_network.py

This PR updates the vertices setter to allow for a list of lists, instead of just a list of tuples.  The change is needed to support reading in JSON files that do not store tuples.
ky10.inp, which includes vertices, was added to the JSON test.
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://usepa.github.io/WNTR/developers.html) and that my contributions are submitted under the [Revised BSD License](https://usepa.github.io/WNTR/license.html).

Updated vertices setter to allow for list of lists

---

wntr/epanet/io.py

To fix issue in #497 
Headloss curve for GPV valves incorrectly used the unit headloss (head/length) type for conversion when reading and writing inp files. Now uses head type instead.
Not a new feature. 
By contributing to this software project, I acknowledge that I have reviewed the [software quality assurance guidelines](https://usepa.github.io/WNTR/developers.html) and that my contributions are submitted under the [Revised BSD License](https://usepa.github.io/WNTR/license.html).

Fix GPV curve conversion from Unit Headloss to Absolute Headloss
